Issue #112 hamburger
ozgurozbek/teothe pull request #116
Opened 2024-11-05 16:05 UTC by kutagorn

I added antd [drawer](https://ant.design/components/drawer) to our mobile menu. 

There was an issue with the submenu's in smaller screen's. I solved it with responsive CSS to adjust submenu positioning for smaller screens. 

There is an other solution with the usage of secondary drawer but after implementing that with the top menu I did not liked how it looked. I still have the file on my computer if anyone want's to take a look at that. I prefered this way tho.

2024-11-05 16:38 UTC, ozgurozbek requested changes
If you could address these issues I'd be happy to merge. Honestly, drawer approach is good if you could instead put [the inline menu from antd](https://ant.design/components/menu/#menu-demo-inline) inside it. Please please please make sure you aren't loading the same menu twice in the page. Navbar loads in every page, and is very crucial for navigation and performance.

2024-11-05 16:38 UTC, ozgurozbek commented on src/app/globals.css
> +    left: 0 !important;
See, that breaks if screen is wider than submenu+menu width.

![image](https://github.com/user-attachments/assets/f0bf10f2-8aea-4fb0-975a-e66e1ded4c59)

2024-11-05 16:38 UTC, ozgurozbek commented on src/components/Navbar.tsx
> +          style={{
![image](https://github.com/user-attachments/assets/17f8940c-8e4c-4422-adbd-0d2a8b0947a1)

Not happy with the styling unfortunately. Would prefer it if it was larger and without the typical bordering etc.

2024-11-05 16:38 UTC, ozgurozbek commented on src/components/Navbar.tsx
> +  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
Decent way to implement drawer honestly. If there was a built-in component that could be better utilized but the built in navbar is not that good anyway.

2024-11-05 16:38 UTC, ozgurozbek commented on src/components/Navbar.tsx
> +          className="hidden md:flex"
![image](https://github.com/user-attachments/assets/7622e62b-0d9f-4722-a79a-f3637756838a)

So what to do if that doesn't work 😂 See what's next to the logo.

2024-11-05 16:38 UTC, ozgurozbek commented on src/components/Navbar.tsx
> +  const menuItems = [
Okay to move it outside if you want to call the menu from multiple places, but doing so in the same component and then calling it twice loads the whole menu twice.

![image](https://github.com/user-attachments/assets/a45bc2b4-87a1-412f-aa9b-2d4a2877b72e)

2024-11-22 12:26 UTC, kutagorn commented
Thanks for your efforts on this PR. After reviewing the changes, I've decided to close this PR and start fresh with a new branch. I ll try to do it without any bug's this time. This PR created more bug's then it solved.

2024-11-22 12:26 UTC, closed without merging